# Generated by Django 3.2.8 on 2021-10-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.ImageField(upload_to='items/')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=10)),
                ('description', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
