# Generated by Django 3.2.8 on 2021-10-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_filter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
