# Generated by Django 3.2.8 on 2021-10-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_picture_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='permalink',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
