# Generated by Django 3.2.8 on 2021-10-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_picture_permalink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='permalink',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
